"""add_schedule_tables

Revision ID: 0efdfc3988dd
Revises: 746e5844e007
Create Date: 2025-12-31 14:07:19.888289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0efdfc3988dd'
down_revision: Union[str, Sequence[str], None] = '746e5844e007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('schedule_type', sa.Enum('SINGLE', 'DAILY', 'WEEKLY', 'INTERVAL', 'CUSTOM', name='scheduletype'), nullable=True),
    sa.Column('times_of_day', sa.JSON(), nullable=True),
    sa.Column('days_of_week', sa.JSON(), nullable=True),
    sa.Column('interval_days', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('remind_before_minutes', sa.Integer(), nullable=True),
    sa.Column('channels', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reminder_schedules_active', 'reminder_schedules', ['user_id', 'is_active'], unique=False)
    op.create_index('idx_reminder_schedules_user', 'reminder_schedules', ['user_id'], unique=False)
    op.create_table('reminder_cycles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('active_days', sa.Integer(), nullable=False),
    sa.Column('pause_days', sa.Integer(), nullable=False),
    sa.Column('total_cycles', sa.Integer(), nullable=True),
    sa.Column('current_cycle', sa.Integer(), nullable=True),
    sa.Column('cycle_start_date', sa.Date(), nullable=False),
    sa.Column('is_in_pause', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['reminder_schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_id')
    )
    op.create_table('reminder_instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('remind_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'CONFIRMED', 'MISSED', 'SNOOZED', name='reminderstatus'), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('snoozed_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('channels_used', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['reminder_schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reminder_instances_pending', 'reminder_instances', ['remind_at', 'status'], unique=False)
    op.create_index('idx_reminder_instances_retry', 'reminder_instances', ['next_retry_at', 'status'], unique=False)
    op.create_index('idx_reminder_instances_schedule', 'reminder_instances', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_reminder_instances_remind_at'), 'reminder_instances', ['remind_at'], unique=False)
    op.create_table('schedule_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('item_type', sa.Enum('EVENT', 'TASK', 'REMINDER', 'RECURRING', name='itemtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'MISSED', name='itemstatus'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remind_before_minutes', sa.Integer(), nullable=True),
    sa.Column('channels', sa.JSON(), nullable=True),
    sa.Column('schedule_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('google_event_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['reminder_schedules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_schedule_items_due', 'schedule_items', ['due_at'], unique=False)
    op.create_index('idx_schedule_items_start', 'schedule_items', ['start_at'], unique=False)
    op.create_index('idx_schedule_items_user', 'schedule_items', ['user_id'], unique=False)
    op.create_index('idx_schedule_items_user_status', 'schedule_items', ['user_id', 'status'], unique=False)
    op.create_table('notification_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instance_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['reminder_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notification_logs_instance', 'notification_logs', ['instance_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_notification_logs_instance', table_name='notification_logs')
    op.drop_table('notification_logs')
    op.drop_index('idx_schedule_items_user_status', table_name='schedule_items')
    op.drop_index('idx_schedule_items_user', table_name='schedule_items')
    op.drop_index('idx_schedule_items_start', table_name='schedule_items')
    op.drop_index('idx_schedule_items_due', table_name='schedule_items')
    op.drop_table('schedule_items')
    op.drop_index(op.f('ix_reminder_instances_remind_at'), table_name='reminder_instances')
    op.drop_index('idx_reminder_instances_schedule', table_name='reminder_instances')
    op.drop_index('idx_reminder_instances_retry', table_name='reminder_instances')
    op.drop_index('idx_reminder_instances_pending', table_name='reminder_instances')
    op.drop_table('reminder_instances')
    op.drop_table('reminder_cycles')
    op.drop_index('idx_reminder_schedules_user', table_name='reminder_schedules')
    op.drop_index('idx_reminder_schedules_active', table_name='reminder_schedules')
    op.drop_table('reminder_schedules')
    # ### end Alembic commands ###
