"""add_user_settings_and_rules

Revision ID: 746e5844e007
Revises: c67bdc05acb6
Create Date: 2025-12-31 04:16:14.833960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '746e5844e007'
down_revision: Union[str, Sequence[str], None] = 'c67bdc05acb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ai_role', sa.String(length=50), nullable=True),
    sa.Column('thinking_depth', sa.String(length=30), nullable=True),
    sa.Column('response_style', sa.String(length=20), nullable=True),
    sa.Column('confrontation_level', sa.String(length=20), nullable=True),
    sa.Column('initiative_level', sa.String(length=30), nullable=True),
    sa.Column('intervention_frequency', sa.String(length=30), nullable=True),
    sa.Column('allowed_actions', sa.JSON(), nullable=True),
    sa.Column('save_policy', sa.String(length=30), nullable=True),
    sa.Column('auto_archive_days', sa.Integer(), nullable=True),
    sa.Column('memory_trust_level', sa.String(length=20), nullable=True),
    sa.Column('saved_types', sa.JSON(), nullable=True),
    sa.Column('analytics_types', sa.JSON(), nullable=True),
    sa.Column('analytics_aggressiveness', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('trigger', sa.String(length=30), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('context_topic_id', sa.UUID(), nullable=True),
    sa.Column('context_mode', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['context_topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rules_active', 'rules', ['is_active'], unique=False)
    op.create_index('idx_rules_scope', 'rules', ['scope'], unique=False)
    op.create_index('idx_rules_user', 'rules', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_rules_user', table_name='rules')
    op.drop_index('idx_rules_scope', table_name='rules')
    op.drop_index('idx_rules_active', table_name='rules')
    op.drop_table('rules')
    op.drop_table('user_settings')
    # ### end Alembic commands ###
