"""add_explain_mode_and_email

Revision ID: afc33fac0647
Revises: 0efdfc3988dd
Create Date: 2025-12-31 14:35:54.474442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afc33fac0647'
down_revision: Union[str, Sequence[str], None] = '0efdfc3988dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('explain_mode', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    op.drop_column('user_settings', 'explain_mode')
    # ### end Alembic commands ###
