"""Add User model and security updates

Revision ID: d9b582f38d71
Revises: 002_add_cal_tables
Create Date: 2025-12-30 02:46:49.337068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9b582f38d71'
down_revision: Union[str, Sequence[str], None] = '002_add_cal_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.drop_index('idx_memory_relations_source', table_name='memory_relations')
    op.drop_index('idx_memory_relations_target', table_name='memory_relations')
    op.drop_table('memory_relations')
    op.drop_index('idx_memory_embeddings_vector', table_name='memory_embeddings', postgresql_using='hnsw')
    op.drop_constraint('memory_embeddings_memory_id_fkey', 'memory_embeddings', type_='foreignkey')
    op.create_foreign_key(None, 'memory_items', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_constraint(None, 'memory_items', type_='foreignkey')
    op.create_foreign_key('memory_embeddings_memory_id_fkey', 'memory_embeddings', 'memory_items', ['memory_id'], ['id'], ondelete='CASCADE')
    op.create_index('idx_memory_embeddings_vector', 'memory_embeddings', ['embedding'], unique=False, postgresql_using='hnsw')
    op.create_table('memory_relations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('target_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('relation_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['memory_items.id'], name='memory_relations_source_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['memory_items.id'], name='memory_relations_target_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='memory_relations_pkey')
    )
    op.create_index('idx_memory_relations_target', 'memory_relations', ['target_id'], unique=False)
    op.create_index('idx_memory_relations_source', 'memory_relations', ['source_id'], unique=False)
    op.drop_table('users')
    # ### end Alembic commands ###
