"""
Digital Denis — Meta-Analyst Agent
═══════════════════════════════════════════════════════════════════════════

Asynchronous agent for analyzing thinking patterns and generating reports.
Does NOT participate in dialogue.
"""

from typing import Optional, List, Dict, Any
from datetime import datetime, timedelta
from dataclasses import dataclass, field
from enum import Enum

from agents.base import BaseAgent, AgentContext, AgentResponse
from llm.openrouter import openrouter
from llm.base import LLMMessage


class ReportType(Enum):
    """Types of reports Meta-Analyst can generate."""
    TOPIC_TRENDS = "topic_trends"
    DECISION_QUALITY = "decision_quality"
    ANOMALY_ALERT = "anomaly_alert"
    WEEKLY_SUMMARY = "weekly_summary"
    MIND_MAP_UPDATE = "mind_map_update"


@dataclass
class AnalysisReport:
    """Report generated by Meta-Analyst."""
    report_type: ReportType
    content: str
    generated_at: datetime = field(default_factory=datetime.utcnow)
    data: Dict[str, Any] = field(default_factory=dict)
    priority: str = "normal"  # low, normal, high, critical
    requires_attention: bool = False


class MetaAnalystAgent(BaseAgent):
    """
    Meta-Analyst Agent — асинхронный аналитик паттернов мышления.
    
    Ответственности:
    - Анализ паттернов мышления
    - Выявление аномалий
    - Генерация отчётов
    - Обновление графа связей
    
    Особенности:
    - Работает АСИНХРОННО (не в диалоге)
    - Никогда не отвечает пользователю напрямую
    - Результаты отображаются в UI
    - Триггерится по расписанию или при накоплении данных
    """
    
    name = "meta_analyst"
    description = "Async pattern analysis agent"
    participates_in_dialogue = False  # KEY DIFFERENCE
    writes_to_memory = True
    is_synchronous = False  # Async agent
    
    META_ANALYST_PROMPT = """Ты — мета-аналитический модуль системы Digital Denis.

Ты анализируешь ПАТТЕРНЫ мышления пользователя, а не отдельные запросы.

Задачи:
1. Выявление повторяющихся тем
2. Анализ качества принятых решений
3. Обнаружение аномалий в мышлении
4. Построение связей между идеями

Формат отчёта:
## Период анализа
[даты]

## Ключевые темы
- Тема 1 (частота, тренд)
- Тема 2

## Паттерны
[выявленные паттерны мышления]

## Аномалии (если есть)
⚠️ [описание аномалии]

## Рекомендации
[что можно улучшить]
"""
    
    async def process(self, context: AgentContext) -> AgentResponse:
        """
        Meta-Analyst doesn't process regular requests.
        Use analyze_* methods instead.
        """
        return AgentResponse(
            content="Meta-Analyst does not process dialogue requests.",
            agent=self.name,
            save_to_memory=False,
        )
    
    async def analyze_period(
        self, 
        memories: List[Dict[str, Any]],
        period_days: int = 7
    ) -> AnalysisReport:
        """
        Analyze memories over a period.
        
        Args:
            memories: List of memory items to analyze
            period_days: Analysis period in days
            
        Returns:
            AnalysisReport with findings
        """
        if not memories:
            return AnalysisReport(
                report_type=ReportType.WEEKLY_SUMMARY,
                content="Недостаточно данных для анализа.",
                priority="low",
            )
        
        # Prepare context
        memory_summary = self._summarize_memories(memories)
        
        messages = [
            LLMMessage(role="system", content=self.META_ANALYST_PROMPT),
            LLMMessage(role="user", content=f"""
Проанализируй следующие записи за последние {period_days} дней:

{memory_summary}

Подготовь отчёт о паттернах мышления.
""")
        ]
        
        response = await openrouter.complete(messages)
        
        # Check for anomalies
        has_anomalies = "аномал" in response.content.lower() or "⚠️" in response.content
        
        return AnalysisReport(
            report_type=ReportType.WEEKLY_SUMMARY,
            content=response.content,
            priority="high" if has_anomalies else "normal",
            requires_attention=has_anomalies,
            data={
                "period_days": period_days,
                "memories_analyzed": len(memories),
            }
        )
    
    async def detect_anomalies(
        self, 
        recent_memories: List[Dict],
        baseline_memories: List[Dict]
    ) -> AnalysisReport:
        """
        Compare recent behavior with baseline to detect anomalies.
        """
        recent_summary = self._summarize_memories(recent_memories)
        baseline_summary = self._summarize_memories(baseline_memories)
        
        messages = [
            LLMMessage(role="system", content=self.META_ANALYST_PROMPT),
            LLMMessage(role="user", content=f"""
Сравни текущее поведение с базовым и выяви аномалии.

## Базовый период (обычное поведение):
{baseline_summary}

## Текущий период:
{recent_summary}

Есть ли существенные отклонения от обычного паттерна мышления?
""")
        ]
        
        response = await openrouter.complete(messages)
        
        # Determine priority
        critical_markers = ["критич", "срочно", "немедленно", "⚠️⚠️"]
        is_critical = any(m in response.content.lower() for m in critical_markers)
        
        return AnalysisReport(
            report_type=ReportType.ANOMALY_ALERT,
            content=response.content,
            priority="critical" if is_critical else "normal",
            requires_attention=is_critical,
        )
    
    async def extract_topics(
        self, 
        memories: List[Dict]
    ) -> List[Dict[str, Any]]:
        """
        Extract and rank topics from memories.
        
        Returns list of topics with scores.
        """
        memory_summary = self._summarize_memories(memories)
        
        messages = [
            LLMMessage(role="system", content="""
Извлеки ключевые темы из записей.
Верни в формате JSON:
[
  {"topic": "название", "count": число_упоминаний, "trend": "up|down|stable"},
  ...
]
Только JSON, без пояснений.
"""),
            LLMMessage(role="user", content=memory_summary)
        ]
        
        response = await openrouter.complete(messages)
        
        # Try to parse JSON
        import json
        try:
            return json.loads(response.content)
        except json.JSONDecodeError:
            return []
    
    def _summarize_memories(self, memories: List[Dict], max_items: int = 20) -> str:
        """Create summary of memories for analysis."""
        if not memories:
            return "Нет записей."
        
        parts = []
        for mem in memories[:max_items]:
            item_type = mem.get("item_type", "thought")
            content = mem.get("content", "")[:150]
            created = mem.get("created_at", "")
            parts.append(f"[{item_type}] {created}: {content}")
        
        return "\n".join(parts)


# Global instance
meta_analyst_agent = MetaAnalystAgent()
